name: Deploy Azure Function (KonferenscentrumFunc – Flex)

on:
  push:
    branches: ["main"]
    paths:
      - "KonferenscentrumFunc/**"
  workflow_dispatch: {}

env:
  AZURE_FUNCTIONAPP_NAME: "funckonferensapp"   # ditt Function App-namn
  AZURE_RESOURCE_GROUP: "KonferenscentrumRG"   # byt till rätt RG
  PROJECT_PATH: "KonferenscentrumFunc"
  DOTNET_VERSION: "8.0.x"

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-dotnet@v4
        with:
          dotnet-version: ${{ env.DOTNET_VERSION }}

      - name: Restore
        run: dotnet restore "${{ env.PROJECT_PATH }}"

      - name: Publish (Release)
        run: |
          pushd "./${{ env.PROJECT_PATH }}"
          dotnet publish -c Release -o ./output
          popd

      - name: Create ZIP
        run: |
          cd "${{ env.PROJECT_PATH }}/output"
          zip -r ../../app.zip .
          cd -

      - name: Azure Login (OIDC)
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      - name: Deploy ZIP to Function App (Flex)
        run: |
          az functionapp deployment source config-zip \
            --resource-group "${{ env.AZURE_RESOURCE_GROUP }}" \
            --name "${{ env.AZURE_FUNCTIONAPP_NAME }}" \
            --src app.zip
