name: Build & (Optionally) Deploy Azure Function (KonferenscentrumFunc)

on:
  push:
    branches: ["main"]
    paths:
      - "KonferenscentrumFunc/**"
  workflow_dispatch:
    inputs:
      deploy:
        description: "Deploy to Azure?"
        required: true
        default: "false"
        type: choice
        options: ["false","true"]

env:
  AZURE_FUNCTIONAPP_NAME: "funckonferensapp"          # Ditt Function App-namn
  AZURE_FUNCTIONAPP_PACKAGE_PATH: "KonferenscentrumFunc"
  DOTNET_VERSION: "8.0.x"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: ${{ env.DOTNET_VERSION }}

      - name: Restore
        run: dotnet restore "${{ env.AZURE_FUNCTIONAPP_PACKAGE_PATH }}"

      - name: Publish (Release)
        run: |
          pushd "./${{ env.AZURE_FUNCTIONAPP_PACKAGE_PATH }}"
          dotnet publish -c Release -o ./output
          popd

      - name: Inspect published files
        run: ls -R "${{ env.AZURE_FUNCTIONAPP_PACKAGE_PATH }}/output"

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: function-publish
          path: ${{ env.AZURE_FUNCTIONAPP_PACKAGE_PATH }}/output

  deploy:
    # Deploy vid push, eller manuellt om deploy=true
    if: ${{ github.event_name == 'push' || (github.event_name == 'workflow_dispatch' && inputs.deploy == 'true') }}
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: function-publish
          path: ./function-publish

      - name: Deploy to Azure Functions (Flex Consumption)
        uses: Azure/functions-action@v1
        with:
          app-name: ${{ env.AZURE_FUNCTIONAPP_NAME }}
          package: "./function-publish"
          publish-profile: ${{ secrets.FUNCTIONAPP_PUBLISH_PROFILE }}