name: Build & Deploy Function (Publish Profile)

on:
  push:
    branches: [ main ]
    paths:
      - 'KonferenscentrumFunc/**'
  workflow_dispatch:

env:
  PROJECT_PATH_FUNC: KonferenscentrumFunc/KonferenscentrumFunc.csproj
  PUBLISH_DIR: func-publish

jobs:
  build:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.x'
      - run: dotnet restore ${{ env.PROJECT_PATH_FUNC }}
      - run: dotnet build ${{ env.PROJECT_PATH_FUNC }} -c Release --no-restore
      - run: dotnet publish ${{ env.PROJECT_PATH_FUNC }} -c Release -o ${{ env.PUBLISH_DIR }} --no-build
      - uses: actions/upload-artifact@v4
        with:
          name: func-publish
          path: ${{ env.PUBLISH_DIR }}

  deploy:
    runs-on: windows-latest
    needs: build
    steps:
      - uses: actions/download-artifact@v4
        with:
          name: func-publish
          path: ./func-publish
      
      - name: Deploy to Azure Function App (Publish Profile)
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'funckonferensapp'          
          package: ./func-publish
          publish-profile: ${{ secrets.FUNCTIONAPP_PUBLISH_PROFILE }}
